version: '3'

services:
  web-staging:
    build:
      context: ../../
      dockerfile: docker/staging/Dockerfile
    image: web-staging
    container_name: web-staging
    ports:
      - '3002:3000'
